"""empty message

Revision ID: 239bd9914bb7
Revises: 
Create Date: 2025-10-06 19:40:25.200652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239bd9914bb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 1️ Add the column as nullable first (so the DB doesn't complain)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # 2️ Populate existing rows with a default value
    op.execute("UPDATE users SET role = 'both' WHERE role IS NULL")

    # 3️ Finally, make the column non-nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
